- hosts: local-deploy
  connection: local
  gather_facts: yes
  vars:
    platform: gcp 
  pre_tasks:
    - import_tasks: "{{ playbook_dir }}/roles/helm_env/tasks/{{ platform }}/install_{{ platform }}_sdk.yaml"
  roles:
    - helm_env