apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: poc-ingresscontroller-secret
spec:
  secretName: poc-ingresscontroller-secret
  dnsNames:
  - trap.money.com
  issuerRef:
    name: selfsigning-clusterissuer
    kind: ClusterIssuer