---
# vars file for everis-paas-demo
mac_os:
  sdk_version: '238.0.0'
  arc: 'x86_64'

gcp:
  project_id: helical-apricot-222515
  zone: 'us-central1-a'
  resources: ['compute.googleapis.com' ,'container.googleapis.com' ,'cloudbuild.googleapis.com']
  k8s_cluster_name: anis-cartujo
  k8s_min_nodes: 1
  k8s_man_nodes: 6
  k8s_num_nodes: 3
  k8s_admin_sa: trap-money
  k8s_admin_binding: root-sa-binding
  k8s_tiller_sa: tiller
  k8s_tiller_binding: tiller
  sdk_working_directory: /home
  sdk_url: https://sdk.cloud.google.com
  components: ['kubectl',]
  machine_type: n1-standard-2

demo:
  namespaces: 'default'

helm:
  dw_url: https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-amd64.tar.gz
  dw_directory: /home
  pkg_name: helm-v2.13.0-linux-amd64.tar.gz

ingress_controller:
  secret: tm-ingresscontroller-secret

certificate:
  type: "-x509"
  durantion_days: 365
  length: "rsa:2048"
  keyout: "anis_cartujo_key.key"
  certout: "anis_cartujo_cert.pem"
  cn: "trap"
  ou: "money.com"
  outputdir: "/tmp"